# Generated by Django 5.0.1 on 2024-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stockprice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='ticker',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
