# Generated by Django 5.0.1 on 2024-02-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stocks_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
