# Generated by Django 5.0.1 on 2024-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stocks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('stock', 'date')},
        ),
    ]
